version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Pre-build step completed.

  build:
    commands:
      - echo Build started...
      - zip -r backend.zip . -x "*.git*"

artifacts:
  files:
    - backend.zip
  discard-paths: yes
